#define GB_CARTRIDGE_SUCCESS    0
#define GB_CARTRIDGE_FILE_ERROR 1
#define GB_CARTRIDGE_NOSAVE_ERROR 2

#define GB_CARTRIDGE_NAME     0x0134
#define GB_CARTRIDGE_TYPE     0x0147
#define GB_CARTRIDGE_ROM_SIZE 0x0148
#define GB_CARTRIDGE_RAM_SIZE 0x0149